### ISSUE TITLE
Uploading images - Book's covers

### ISSUE THREAD

**Issue by napiorka-design** [napiorka-design/ant#5]
Add files to Images Folder in Ant Repository:

1.  Six(6) images of different book covers (of size 400 x 200).
2.  Three(3) icons(of size 40x40) for:
- Free Shipping,
- Free Returns 
- Low Prices

3. Three(3) images for featured products (size 100 x 125)
4. 
@tasha-jas

**Comment by tasha-jas** [comment]
Issue completed.
